# Generated by Django 2.0.1 on 2018-09-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paying_user',
            field=models.BooleanField(default=False),
        ),
    ]
