# Generated by Django 2.0.1 on 2018-05-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sina_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(default='', max_length=500, verbose_name='展示次数')),
                ('newsId', models.CharField(default='', max_length=500, verbose_name='新闻id')),
                ('title', models.CharField(default='', max_length=500, verbose_name='标题')),
                ('link', models.CharField(default='', max_length=500, verbose_name='链接')),
                ('pic', models.CharField(default='', max_length=500, verbose_name='图片url')),
                ('showTag', models.CharField(default='', max_length=500, verbose_name='标识')),
                ('articlePreload', models.CharField(default='', max_length=500, verbose_name='文章预加载')),
                ('commentStatus', models.CharField(default='', max_length=500, verbose_name='评论状态')),
                ('adid', models.CharField(default='', max_length=500, verbose_name='广告id')),
                ('dislikeTags', models.CharField(default='', max_length=500, verbose_name='是否展示更多')),
                ('creat_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新浪app',
                'verbose_name_plural': '新浪app',
                'db_table': 'sina_app',
            },
        ),
        migrations.CreateModel(
            name='toutiao_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_url', models.CharField(default='', max_length=1024, verbose_name='点击链接')),
                ('display_info', models.CharField(default='', max_length=500, verbose_name='展示消息')),
                ('title', models.CharField(default='', max_length=500, verbose_name='标题')),
                ('display_url', models.CharField(default='', max_length=500, verbose_name='点击链接')),
                ('filter_words', models.CharField(default='', max_length=500, verbose_name='')),
                ('has_video', models.CharField(default='', max_length=500, verbose_name='是否有视频')),
                ('publish_time', models.CharField(default='', max_length=500, verbose_name='发表时间戳')),
                ('read_count', models.CharField(default='', max_length=500, verbose_name='看过的次数')),
                ('share_count', models.CharField(default='', max_length=500, verbose_name='分享次数')),
                ('show_more', models.CharField(default='', max_length=500, verbose_name='是否展示更多')),
                ('source', models.CharField(default='', max_length=500, verbose_name='发布者名称')),
                ('url', models.CharField(default='', max_length=500, verbose_name='点击链接')),
                ('repin_count', models.CharField(default='', max_length=500, verbose_name='')),
                ('label', models.CharField(default='', max_length=500, verbose_name='标签')),
                ('creat_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '今日头条app',
                'verbose_name_plural': '今日头条app',
                'db_table': 'toutiao_app',
            },
        ),
    ]
