# Generated by Django 2.0.1 on 2018-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toutiao_app',
            name='creat_time',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='display_info',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='display_url',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='filter_words',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='has_video',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='label',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='repin_count',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='share_count',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='share_url',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='show_more',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='source',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='title',
        ),
        migrations.RemoveField(
            model_name='toutiao_app',
            name='url',
        ),
        migrations.AddField(
            model_name='toutiao_app',
            name='abstract',
            field=models.CharField(default='', max_length=50, verbose_name='点击链接'),
        ),
        migrations.AddField(
            model_name='toutiao_app',
            name='action_list',
            field=models.TextField(default='', verbose_name='点击链接'),
        ),
    ]
