# Generated by Django 2.0.1 on 2018-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180502_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sina_app',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='sina_app',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
