# Generated by Django 2.0.1 on 2018-05-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20180503_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='souhu_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitorkey', models.CharField(default='', max_length=50, verbose_name='monitorkey')),
                ('resource', models.TextField(default='', verbose_name='resource')),
                ('resource2', models.TextField(default='', verbose_name='resource2')),
                ('weight', models.CharField(default='', max_length=20, verbose_name='weight')),
                ('itemspaceid', models.CharField(default='', max_length=20, verbose_name='itemspaceid')),
                ('resource1', models.TextField(default='', verbose_name='resource1')),
                ('impressionid', models.CharField(default='', max_length=50, verbose_name='article_sub_type')),
                ('special', models.TextField(default='', verbose_name='special')),
                ('offline', models.CharField(default='', max_length=80, verbose_name='offline')),
                ('adid', models.CharField(default='', max_length=80, verbose_name='adid')),
                ('viewmonitor', models.CharField(default='', max_length=1000, verbose_name='viewmonitor')),
                ('size', models.CharField(default='', max_length=20, verbose_name='size')),
                ('online', models.CharField(default='', max_length=20, verbose_name='online')),
                ('position', models.CharField(default='', max_length=20, verbose_name='position')),
                ('tag', models.CharField(default='', max_length=20, verbose_name='tag')),
                ('editNews', models.CharField(default='', max_length=10, verbose_name='editNews')),
                ('statsType', models.CharField(default='', max_length=5, verbose_name='statsType')),
                ('isPreload', models.CharField(default='', max_length=5, verbose_name='isPreload')),
                ('newsType', models.CharField(default='', max_length=10, verbose_name='newsType')),
                ('gbcode', models.CharField(default='', max_length=50, verbose_name='gbcode')),
                ('commentNum', models.CharField(default='', max_length=10, verbose_name='commentNum')),
                ('isHasSponsorships', models.CharField(default='', max_length=5, verbose_name='isHasSponsorships')),
                ('recomTime', models.CharField(default='', max_length=5, verbose_name='recomTime')),
                ('newsId', models.CharField(default='', max_length=30, verbose_name='newsId')),
                ('iconNight', models.TextField(default='', verbose_name='iconNight')),
                ('isWeather', models.CharField(default='', max_length=5, verbose_name='isWeather')),
                ('isRecom', models.CharField(default='', max_length=5, verbose_name='isRecom')),
                ('iconText', models.CharField(default='', max_length=10, verbose_name='iconText')),
                ('iconDay', models.TextField(default='', verbose_name='iconDay')),
                ('link', models.TextField(default='', verbose_name='link')),
                ('abposition', models.CharField(default='', max_length=10, verbose_name='abposition')),
                ('adType', models.CharField(default='', max_length=5, verbose_name='adType')),
                ('playTime', models.CharField(default='', max_length=20, verbose_name='playTime')),
                ('adp_type', models.CharField(default='', max_length=10, verbose_name='adp_type')),
                ('isFlash', models.CharField(default='', max_length=5, verbose_name='isFlash')),
                ('isHasTv', models.CharField(default='', max_length=5, verbose_name='isHasTv')),
                ('newschn', models.CharField(default='', max_length=5, verbose_name='newschn')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '搜狐app',
                'verbose_name_plural': '搜狐app',
                'db_table': 'souhu_app',
            },
        ),
    ]
