# Generated by Django 2.0.1 on 2018-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_souhu_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toutiao_app',
            name='creat_time',
        ),
        migrations.AddField(
            model_name='sina_app',
            name='amount',
            field=models.IntegerField(default='1', max_length=11, verbose_name='爬取次数'),
        ),
        migrations.AddField(
            model_name='souhu_app',
            name='amount',
            field=models.IntegerField(default='1', max_length=11, verbose_name='爬取次数'),
        ),
        migrations.AddField(
            model_name='toutiao_app',
            name='amount',
            field=models.IntegerField(default='1', max_length=11, verbose_name='爬取次数'),
        ),
        migrations.AddField(
            model_name='toutiao_app',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='toutiao_app',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sina_app',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sina_app',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='souhu_app',
            name='adid',
            field=models.CharField(default='', max_length=80, verbose_name='广告id'),
        ),
        migrations.AlterField(
            model_name='souhu_app',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='souhu_app',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
