# Generated by Django 2.0.1 on 2018-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20180811_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='channel',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='header',
            field=models.TextField(default='', null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='media',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.TextField(default='', null=True, verbose_name='parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='system',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='system'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='url',
            field=models.TextField(default='', null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='toutiao_ad_to_parameter',
            name='toutiao_ad_id',
            field=models.IntegerField(default='1', null=True, verbose_name='toutiao_ad_id'),
        ),
        migrations.AlterField(
            model_name='toutiao_ad_to_parameter',
            name='toutiao_para_id',
            field=models.IntegerField(default='1', null=True, verbose_name='toutiao_para_id'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='LBS_status',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='LBS_status'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='_as',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='_as'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ab_client',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='ab_client'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ab_feature',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='ab_feature'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ab_group',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='ab_group'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ab_version',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='ab_version'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ac',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='ac'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='aid',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='aid'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='app_name',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='channel',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='channel'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='city',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='concern_id',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='concern_id'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='count',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='cp',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='cp'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='detail',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='device_id',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='device_id'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='device_platform',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='device_platform'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='device_type',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='device_type'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='fp',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='fp'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='header',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='idfa',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='idfa'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='idfv',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='idfv'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='iid',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='iid'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='image',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='language',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='last_refresh_sub_entrance_interval',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='last_refresh_sub_entrance_interval'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='list_count',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='list_count'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='loc_mode',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='loc_mode'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='min_behot_time',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='min_behot_time'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='openudid',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='openudid'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='os_version',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='os_version'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='refer',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='refer'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='refresh_reason',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='refresh_reason'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='resolution',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='session_refresh_idx',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='session_refresh_idx'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ssmix',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='ssmix'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='st_time',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='st_time'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='strict',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='strict'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='support_rn',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='support_rn'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='ts',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='ts'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='tt_from',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='tt_from'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='url',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='version_code',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='version_code'),
        ),
        migrations.AlterField(
            model_name='toutiao_parameter',
            name='vid',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='vid'),
        ),
    ]
